### ISSUE TITLE
在服务器报错

### ISSUE THREAD

**Issue by xmengnet** [sihuan/XZZ#31]
在服务器执行` python main.py` 后，一直有下面的错误：
```
[2021-03-30 19:29:17,695] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/XZZ/XZZ/main.py", line 9, in whenmsg
    ZZRouter(request.get_json())
  File "/root/XZZ/XZZ/route.py", line 5, in ZZRouter
    uid = data['user_id']
KeyError: 'user_id'
127.0.0.1 - - [30/Mar/2021 19:29:17] "POST / HTTP/1.1" 500 -

```
不停的刷新这几句错误，最终导致服务器都卡了，ssh都登不上，只能重启。请问这几句报错应该怎么处理？

**Comment by sihuan** [comment]
你的上报格式是 array 还是 string 呢，如果是string 的话，请改成 array，很抱歉做了这个更改没有修改文档

**Comment by xmengnet** [comment]
好了，感谢已经正常了!

**Comment by zsbai** [comment]
我修改为array还是一直报错啊...

**Comment by zsbai** [comment]
127.0.0.1 - - [09/Jul/2021 00:19:10] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/bailu/bot/XZZ/main.py", line 9, in whenmsg
    ZZRouter(request.get_json())
  File "/usr/bailu/bot/XZZ/route.py", line 5, in ZZRouter
    uid = data['user_id']
KeyError: 'user_id'

**Comment by zsbai** [comment]
127.0.0.1 - - [09/Jul/2021 00:32:51] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/bailu/bot/XZZ/main.py", line 9, in whenmsg
    ZZRouter(request.get_json())
  File "/usr/bailu/bot/XZZ/route.py", line 5, in ZZRouter
    uid = data['user_id']
KeyError: 'user_id'

改为array后仍然提示这样...

**Comment by sihuan** [comment]
> 127.0.0.1 - - [09/Jul/2021 00:32:51] "POST / HTTP/1.1" 500 -
> Traceback (most recent call last):
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2463, in **call**
> return self.wsgi_app(environ, start_response)
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
> response = self.handle_exception(e)
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
> raise value
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
> raise value
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/bailu/bot/XZZ/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/usr/bailu/bot/XZZ/main.py", line 9, in whenmsg
> ZZRouter(request.get_json())
> File "/usr/bailu/bot/XZZ/route.py", line 5, in ZZRouter
> uid = data['user_id']
> KeyError: 'user_id'
> 
> 改为array后仍然提示这样...

可以贴一下配置吗，注意隐去隐私部分

**Comment by zsbai** [comment]
# go-cqhttp 默认配置文件

account: # 账号相关
  uin: xxxx # QQ账号
  password: 'xxxx空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 是否启用 DEBUG
  debug: false # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # HTTP 通信设置
  - http:
      # 服务端监听地址
      host: 0.0.0.0
      # 服务端监听端口
      port: 5900
      # 反向HTTP超时时间, 单位秒
      # 最小值为5，小于5将会忽略本项设置
      timeout: 5
      middlewares:
        <<: *default # 引用默认中间件
      # 反向HTTP POST地址列表
      post:
      - url: '127.0.0.1:5580' # 地址
        secret: ''           # 密钥


config.py基本没有变化

**Comment by sihuan** [comment]
你在使用哪个版本的 go-cqhttp

**Comment by zsbai** [comment]
> 你在使用哪个版本的 go-cqhttp

最新release里的版本

**Comment by sihuan** [comment]
> > 你在使用哪个版本的 go-cqhttp
> 
> 最新release里的版本

我刚刚拉了 go-cqhttp 和 xzz 的最新配置，跑起来没什么问题诶。。

**Comment by sihuan** [comment]
> > 你在使用哪个版本的 go-cqhttp
> 
> 最新release里的版本

你是在执行什么命令的时候收到的报错呢，消息过滤有没有配置好
```json
{
    "message_type": "group",
    "raw_message":{
        ".regex":"^\/"
    },
    "user_id":{
        ".neq": 80000000
    }
}
```

消息过滤要配置成这样，不然会收到非预期的消息

**Comment by zsbai** [comment]
emmmm我再试一下

**Comment by zsbai** [comment]
草，不好意思。。。。发现端口是错的，一个是6000一个是6700

**Comment by zsbai** [comment]
已查明原因，可以关闭issue了
